repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: ruff-fix
        name: ruff fix
        entry: task fix
        language: system
        types: [python]
        pass_filenames: false
        exclude: ^frontend/

  - repo: local
    hooks:
      - id: mypy
        name: mypy type check
        entry: task check
        language: system
        types: [python]
        pass_filenames: false
        exclude: ^frontend/
