services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv  # Exclude .venv from sync to avoid conflicts
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
    command: uv run uvicorn prai.app:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Exclude node_modules from sync to avoid conflicts
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - backend

networks:
  default:
    name: prai-dev
