version: 3

tasks:
  install:
    desc: Install dependencies
    cmds:
      - uv sync

  test:
    desc: Run tests
    cmds:
      - uv run pytest

  check:
    desc: Run checks
    cmds:
      - uv run ruff check --fix
      - uv run mypy src