version: 3

tasks:
  install:
    desc: Install dependencies
    cmds:
      - uv sync

  test:
    desc: Run tests
    cmds:
      - uv run pytest

  lint:
    desc: Run linting checks
    cmds:
      - uv run ruff check

  fix:
    desc: Run linting with auto-fix
    cmds:
      - uv run ruff check --fix

  check:
    desc: Run type checking
    cmds:
      - uv run mypy src/prai