# generated by datamodel-codegen:
#   filename:  user-schema.json
#   timestamp: 2025-07-29T03:35:38+00:00

from __future__ import annotations
from pydantic import AnyUrl, BaseModel, ConfigDict, EmailStr, Field, RootModel
from datetime import datetime


class Plan(BaseModel):
    collaborators: int
    name: str
    space: int
    private_repos: int


class PrivateUser(BaseModel):
    """
    Private User
    """

    login: str = Field(..., examples=["octocat"])
    id: int = Field(..., examples=[1])
    user_view_type: str | None = None
    node_id: str = Field(..., examples=["MDQ6VXNlcjE="])
    avatar_url: AnyUrl = Field(..., examples=["https://github.com/images/error/octocat_happy.gif"])
    gravatar_id: str | None = Field(..., examples=["41d064eb2195891e12d0413f63227ea7"])
    url: AnyUrl = Field(..., examples=["https://api.github.com/users/octocat"])
    html_url: AnyUrl = Field(..., examples=["https://github.com/octocat"])
    followers_url: AnyUrl = Field(..., examples=["https://api.github.com/users/octocat/followers"])
    following_url: str = Field(..., examples=["https://api.github.com/users/octocat/following{/other_user}"])
    gists_url: str = Field(..., examples=["https://api.github.com/users/octocat/gists{/gist_id}"])
    starred_url: str = Field(..., examples=["https://api.github.com/users/octocat/starred{/owner}{/repo}"])
    subscriptions_url: AnyUrl = Field(..., examples=["https://api.github.com/users/octocat/subscriptions"])
    organizations_url: AnyUrl = Field(..., examples=["https://api.github.com/users/octocat/orgs"])
    repos_url: AnyUrl = Field(..., examples=["https://api.github.com/users/octocat/repos"])
    events_url: str = Field(..., examples=["https://api.github.com/users/octocat/events{/privacy}"])
    received_events_url: AnyUrl = Field(..., examples=["https://api.github.com/users/octocat/received_events"])
    type: str = Field(..., examples=["User"])
    site_admin: bool
    name: str | None = Field(..., examples=["monalisa octocat"])
    company: str | None = Field(..., examples=["GitHub"])
    blog: str | None = Field(..., examples=["https://github.com/blog"])
    location: str | None = Field(..., examples=["San Francisco"])
    email: EmailStr | None = Field(..., examples=["octocat@github.com"])
    notification_email: EmailStr | None = Field(default=None, examples=["octocat@github.com"])
    hireable: bool | None = None
    bio: str | None = Field(..., examples=["There once was..."])
    twitter_username: str | None = Field(default=None, examples=["monalisa"])
    public_repos: int = Field(..., examples=[2])
    public_gists: int = Field(..., examples=[1])
    followers: int = Field(..., examples=[20])
    following: int = Field(..., examples=[0])
    created_at: datetime = Field(..., examples=["2008-01-14T04:33:35Z"])
    updated_at: datetime = Field(..., examples=["2008-01-14T04:33:35Z"])
    private_gists: int = Field(..., examples=[81])
    total_private_repos: int = Field(..., examples=[100])
    owned_private_repos: int = Field(..., examples=[100])
    disk_usage: int = Field(..., examples=[10000])
    collaborators: int = Field(..., examples=[8])
    two_factor_authentication: bool = Field(..., examples=[True])
    plan: Plan | None = None
    business_plus: bool | None = None
    ldap_dn: str | None = None


class PublicUser(BaseModel):
    """
    Public User
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    login: str
    id: int
    user_view_type: str | None = None
    node_id: str
    avatar_url: AnyUrl
    gravatar_id: str | None = None
    url: AnyUrl
    html_url: AnyUrl
    followers_url: AnyUrl
    following_url: str
    gists_url: str
    starred_url: str
    subscriptions_url: AnyUrl
    organizations_url: AnyUrl
    repos_url: AnyUrl
    events_url: str
    received_events_url: AnyUrl
    type: str
    site_admin: bool
    name: str | None = None
    company: str | None = None
    blog: str | None = None
    location: str | None = None
    email: EmailStr | None = None
    notification_email: EmailStr | None = None
    hireable: bool | None = None
    bio: str | None = None
    twitter_username: str | None = None
    public_repos: int
    public_gists: int
    followers: int
    following: int
    created_at: datetime
    updated_at: datetime
    plan: Plan | None = None
    private_gists: int | None = Field(default=None, examples=[1])
    total_private_repos: int | None = Field(default=None, examples=[2])
    owned_private_repos: int | None = Field(default=None, examples=[2])
    disk_usage: int | None = Field(default=None, examples=[1])
    collaborators: int | None = Field(default=None, examples=[3])


class Model(RootModel[PrivateUser | PublicUser]):
    root: PrivateUser | PublicUser
